travis:
  secure:
    BINSTAR_TOKEN: M26llpb5nrAiX+5vVc4yURu/pAaCkqHrNO1Y0/x4rM7RpQg8YjxQW71qvgilfP7Qipqef0eeA7q/i85Gh1W8zZfRnJeL9wVceftBN3I2NQcB5F2LiDDG2nVzTzxtEBVf0W+e72bQO9d9/RGvEEvcFqVrGFP9GJF2asSHYvNgE6aBfLF9rnCj64hftMT+aFje1Q5RNLpyev8TIe2d3QP6N5d2y7PMAtS4xzdhwasaRQvJ38A+/NXttLKAnPFqL2pvfynnevpSc9ywPadi2qNPRj9K1Jf7I/i6jc+S98IYtj6jUvhVgNJCzxgphO3b2obxChdnjDUkEtWckZurjtfqVQvN8Y+iZhubYKoIkrUrp0445/xg6g/1uWVeMX4s192VOq45xO3d/Ie6Y8UponnxDEdkEpt7O8ZqWDHxJnel5jZOBjWiyhaMpYV1dGvr9jEXN+a9w8kt9uAqGu6SmDGFn3SSopTYa3dF1RdbjA/Kxj1yYGhnE2U2ViKayQPq3ue/rsCYSJGumLklVQlGx+CTaGFRYlQG0ekVdoQGkZqvBsejjSE7whXhQSwpoW54Npg1UY7INie5AIGiIW0MOcIy1D7eRvbVBSAbgtoxDZ5BszQZIu/CwNAJ8nDF5afIR973V0YyZ7s9tWhHzYo5kUG+xbVJOGdRLBYnTApYdCuY/V4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
